---
title: "Iteration_and_listcols"
output: github_document
---



```{r}
library(tidyverse)
library(rvest)
library(readxl)
```


Set seed for reproducibility.

```{r}
set.seed(1)
```



### lists

```{r}
vec_numeric = 5:8
vec_char = c("My", "name", "is", "Jeff")
vec_logical = c(TRUE, TRUE, TRUE, FALSE)
```

Different stuff with different lengths

```{r}
l = list(
  vec_numeric = 1:5,
  vec_char = LETTERS,
  matrix = matrix(1:10, nrow = 5, ncol = 2),
  summary = summary(rnorm(100))
)

```

Accessing lists

```{r}
l$vec_char
l[[2]]
l[["summary"]]
```


### loops

```{r}
list_norm_sample =
  list(
    a = rnorm(20, 2, 5),
    b = rnorm(20, 0, 7),
    c = rnorm(20, 10, .2),
    d = rnorm(20, -3, 1)
  )
```

mean and sd function

```{r}
mean_and_sd = function(x) {
  
  if(!is.numeric(x)) {
    stop("Argument should be numbers")
  } else if (length(x) < 2) {
    stop("You need at least 2 numbers to get z scores")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
  
}
```

```{r}
mean_and_sd(list_norm_sample$a)
mean_and_sd(list_norm_sample$b)
mean_and_sd(list_norm_sample$c)
mean_and_sd(list_norm_sample$d)
```


```{r}
output = vector("list", length = 4)

for(i in 1:4) {
  
  output[[i]] = mean_and_sd(list_norm_sample[[i]])
  
}

output
```


### use `map`

```{r}
output = map(list_norm_sample, mean_and_sd)

map(list_norm_sample, summary)
```



### create DF

```{r}
listcol_df =
  tibble(
    name = c("a", "b", "c", "d"),
    samp = list_norm_sample
  )
```

```{r}
map(listcol_df$samp, mean_and_sd)

listcol_df |>
  mutate(
    mean_sd = map(samp, mean_and_sd),
    median = map(samp, median)
    ) |>
  select(name, mean_sd) |>
  unnest(mean_sd)
```


### NSDUH

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)
```

Import function.

```{r}
nsduh_import = function(html, table_number, outcome_name) {
  
  html |> 
  html_table() |> 
  nth(table_number) |>
  slice(-1) |> 
  select(-contains("P Value")) |>
  pivot_longer(
    -State,
    names_to = "age_year", 
    values_to = "percent") |>
  separate(age_year, into = c("age", "year"), sep = "\\(") |>
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$", ""),
    percent = as.numeric(percent),
    outcome = outcome_name) |>
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
  
}

nsduh_import(nsduh_html, 1, "marj")
nsduh_import(nsduh_html, 4, "cocaine")
nsduh_import(nsduh_html, 5, "heroine")
```




import data using a `for` loop.

```{r}
table_input = list(1, 4, 5)
name_input = list("marj", "cocaine", "heroine")

output = vector("list", length = 3)

for(i in 1:3) {
  
  output[[i]] = nsduh_import(nsduh_html, table_input[[i]], name_input[[i]])
  
}

nsduh_df = bind_rows(output)
```


Try again, using maps!

```{r}
nsduh_import = function(html, table_number) {
  
  html |> 
  html_table() |> 
  nth(table_number) |>
  slice(-1) |> 
  select(-contains("P Value")) |>
  pivot_longer(
    -State,
    names_to = "age_year", 
    values_to = "percent") |>
  separate(age_year, into = c("age", "year"), sep = "\\(") |>
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$", ""),
    percent = as.numeric(percent)) |>
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
  
}

nsduh_df = 
  tibble(
    name = c("marj", "cocaine", "heroine"),
    number = c(1, 4, 5)
  ) |>
  mutate(table = map(number, nsduh_import, html = nsduh_html)) |>
  unnest(table)

```

### revisit the weather df

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


```{r}
weather_nest_df = 
  weather_df |>
  nest(df = date:tmin)
```

can I regress `tmax` on `tmin` for each of these...?

```{r}
central_park_df = 
  weather_nest_df |>
  pull(df) |>
  nth(1)
```

fit a linear regression for central park

```{r}
weather_lm = function(df) {
  lm(tmax ~ tmin, data = df)
}

weather_lm(central_park_df)
```

Let's try a `for` loop

```{r}
input_list = weather_nest_df |> pull(df)
output = vector("list", length = 3)

for(i in 1:3) {
  output[[i]] = weather_lm(input_list[[i]])
}

weather_nest_df |>
  mutate(models = map(df, weather_lm))
```

