---
title: "writing_functions"
output: github_document
---



```{r}
library(tidyverse)
library(rvest)
```


Set seed for reproducibility.

```{r}
set.seed(12345)
```


## Z score function

Z scores subtract the mean and devide by the sd.

```{r}
x_vec = rnorm(20, mean = 5, sd = .3)
```

Compute Z score for `x_vec.

```{r}
(x_vec - mean(x_vec)) / sd(x_vec)
```

Write a function to do this!

```{r}
z_score = function(x) {
  
  if(!is.numeric(x)) {
    stop("Argument should be numbers")
  } else if (length(x) < 2) {
    stop("You need at least 2 numbers to get z scores")
  }
  
  z = (x - mean(x)) / sd(x)
  
  z
  
}
```

Check that this works.

```{r}
z_score(x = x_vec)
```

Keep checking.

```{r, error = TRUE}
z_score(x = 3) 

z_score(c("my", "name", "is", "Jess")) 

z_score(c(TRUE, TRUE, FALSE, TRUE))

z_score(iris) 
```


### Multiple outputs.

```{r}
mean_and_sd = function(x) {
  
  if(!is.numeric(x)) {
    stop("Argument should be numbers")
  } else if (length(x) < 2) {
    stop("You need at least 2 numbers to get z scores")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
  
}
```

Double check I did this right ...

```{r}
mean_and_sd(x_vec)
```


### Start getting means ad sds

```{r}

x_vec = rnorm(n = 30, mean = 5, sd = .5)

tibble(
  mean = mean(x_vec),
  sd = sd(x_vec)
)


```

Let's write a function that uses `n`, a true mean, and true SD as inputs.

```{r}
sim_mean_sd = function(n_obs, mu = 5, sigma = 1) {
  
  x_vec = rnorm(n = n_obs, mean = mu, sd = sigma)

  tibble(
    mean = mean(x_vec),
    sd = sd(x_vec)
  )
  
}

sim_mean_sd(n_obs = 30, mu = 50, sigma = .5)
sim_mean_sd(n_obs = 100)
sim_mean_sd(12, 24, 4)
sim_mean_sd(mu = 0, n_obs = 24, 4)
```

